[package]
name = "dice"
version = "0.1.0"
authors = ["Isak JÃ¤gberg <ijagberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.9"
regex = "1.3.4"
rand = "0.7.3"
lazy_static = "1.4.0"
